name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: homework
          POSTGRES_PASSWORD: homework
          POSTGRES_DB: homework_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U homework" 
          --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: homework_test
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: homework

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h ${{ env.POSTGRES_HOST }} -p ${{ env.POSTGRES_PORT }}; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Initialize DB
        run: |
          python - <<'PYCODE'
          from dotenv import load_dotenv
          load_dotenv()
          from sqlmodel import SQLModel
          from app.db.session import engine
          SQLModel.metadata.create_all(engine)
          PYCODE

      - name: Run tests
        run: |
          pytest -q
